Drop ruby-2.3 due to the following error of rubocop
https://circleci.com/gh/masutaka/circleci-bundle-update-pr/703

Error: RuboCop found unsupported Ruby version 2.3 in `TargetRubyVersion` parameter (in .rubocop.yml). 2.3-compatible analysis was dropped after version 0.82.
Supported versions: 2.4, 2.5, 2.6, 2.7