Drop ruby-2.4 due to the following error of rubocop
https://app.circleci.com/pipelines/github/masutaka/circleci-bundle-update-pr/211/workflows/2e61c6a3-2dc0-44ea-936d-b09228815569/jobs/1134

Error: RuboCop found unsupported Ruby version 2.4 in `TargetRubyVersion` parameter (in .rubocop.yml). 2.4-compatible analysis was dropped after version 1.12.
Supported versions: 2.5, 2.6, 2.7, 3.0